services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anurag_app
    ports:
      - "5175:5175"
    volumes:
      - .:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - TZ=Asia/Kolkata
    restart: unless-stopped
